import UIKit

struct StringConstants {
    static let kLblFeb: String = "Feb"
    static let kLblJun: String = "Jun"
    static let k: String = ""
    static let kLblGoodMorning: String = "Good morning"
    static let kLblJul: String = "Jul"
    static let kLblDashboard: String = "Dashboard"
    static let kMsg22Aug23Sep: String = "22 Aug - 23 Sept"
    static let kLbl0: String = "0"
    static let kLblTalkWithUs: String = "Talk with us"
    static let kLbl25: String = "25"
    static let kLblAug: String = "Aug"
    static let kLbl123: String = "123"
    static let kMsgHttpsSamplel: String = "https://samplelink.oia.bio/ashd..."
    static let kLbl100: String = "100"
    static let kLblAhamedab: String = "Ahamedabad"
    static let kLbl22Aug2022: String = "22 Aug 2022"
    static let kLblInstagram: String = "Instagram"
    static let kLbl2323: String = "2323"
    static let kLblOverview: String = "Overview"
    static let kLblViewAllLinks: String = "View all Links"
    static let kLblApr: String = "Apr"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblBestTime: String = "Best Time"
    static let kLblTopLinks: String = "Top Links"
    static let kLblClicks: String = "Clicks"
    static let kLbl75: String = "75"
    static let kLblMay: String = "May"
    static let kLbl50: String = "50"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblViewAnalytics: String = "View Analytics"
    static let kLblMar: String = "Mar"
    static let kLblTopSource: String = "Top source"
    static let kLblAjayManva: String = "Ajay Manva"
    static let kLblJan: String = "Jan"
    static let kLblTodaySClicks: String = "Today’s clicks"
    static let kLblRecentLinks: String = "Recent Links"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLbl11001200: String = "11:00 - 12:00"
    static let kMsgSampleLinkNam: String = "Sample link name..."
    static let kMsgFrequentlyAske: String = "Frequently Asked Questions"
    static let kLblTopLocation: String = "Top Location"
}
